-- 1. Create the 'posts' table
CREATE TABLE IF NOT EXISTS public.posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT,
    description TEXT,
    video_id TEXT,
    duration TEXT,
    cover_image_url TEXT,
    published BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the 'site_settings' table
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name TEXT DEFAULT 'Minimal Vlog',
    site_description TEXT,
    about_bio TEXT,
    twitter_url TEXT,
    youtube_url TEXT,
    instagram_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Insert default settings (so the row exists)
INSERT INTO public.site_settings (id, site_name)
VALUES (1, 'Minimal Vlog')
ON CONFLICT (id) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Allow Public Read, Admin All)
-- Allow everyone to read published posts
CREATE POLICY "Public can view published posts" 
ON public.posts FOR SELECT 
USING (published = true);

-- Allow authenticated (admin) users to do everything with posts
CREATE POLICY "Admins can manage posts" 
ON public.posts FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Allow everyone to view site settings
CREATE POLICY "Public can view site settings" 
ON public.site_settings FOR SELECT 
USING (true);

-- Allow admins to update site settings
CREATE POLICY "Admins can update site settings" 
ON public.site_settings FOR UPDATE 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 6. Storage Policies for 'media' bucket
-- Note: You must create the bucket 'media' manually in the Storage dashboard if it doesn't exist.
-- These policies allow public read and admin upload.
-- (Run these only if you can't set them in the UI)

-- Allow public access to media
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'media' );

-- Allow authenticated uploads
CREATE POLICY "Auth Upload"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'media' );
